Repository vuejs/composition-api, pull requests merged in 2020-06, with the labels that each got.

#277 Fix(computed): destroy helper vm of computed to prevent memleak (fix #270)
  src/apis/computed.ts
Labels: PR:Bugfix, PR:Review-required

#397 docs: guide users to use versioned CDN
  README.md
  README.zh-CN.md
  package.json
  scripts/update-readme.js
Labels: v1.0

#398 BREAKING CHANGE: drop createComponent
  src/component/component.ts
  src/component/index.ts
  src/index.ts
  test/types/defineComponent.spec.ts
Labels: BREAKING CHANGE, v1.0

#400 BREAKING CHANGE: rename createElement to h
  src/apis/computed.ts
  src/apis/inject.ts
  src/apis/lifecycle.ts
  src/apis/watch.ts
  src/createElement.ts
  src/helper.ts
  src/index.ts
  src/runtimeContext.ts
  src/setup.ts
  test/setup.spec.js
  test/setupContext.spec.js
  test/templateRefs.spec.js
  test/types/defineComponent.spec.ts
  test/v3/runtime-core/apiLifecycle.spec.ts
Labels: BREAKING CHANGE, v1.0

#399 BREAKING CHANGE: Change umd exported name to `VueCompositionAPI`
  README.md
  README.zh-CN.md
  rollup.config.js
Labels: BREAKING CHANGE, v1.0

#413 BREAKING CHANGE: match dist file naming with vue 2
  index.js
  package.json
  rollup.config.js
Labels: BREAKING CHANGE, v1.0

#390 Preparing for v1.0.0
  README.md
  README.zh-CN.md
  index.js
  package.json
  rollup.config.js
  scripts/update-readme.js
  src/apis/computed.ts
  src/apis/inject.ts
  src/apis/lifecycle.ts
  src/apis/watch.ts
  src/component/defineComponent.ts
  src/component/index.ts
  src/createApp.ts
  src/createElement.ts
  src/helper.ts
  src/index.ts
  src/runtimeContext.ts
  src/setup.ts
  test/createApp.spec.js
  test/setup.spec.js
  test/setupContext.spec.js
  test/templateRefs.spec.js
  test/types/defineComponent.spec.ts
  test/v3/runtime-core/apiLifecycle.spec.ts
Labels: v1.0
